name: PR-Validation

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'FireDispatchStatusApp/**'
      - '.github/workflows/**'
      - '.swiftlint.yml'

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: |
          brew install swiftlint

      - name: Run SwiftLint
        run: |
          swiftlint lint --strict --config .swiftlint.yml

  build:
    name: Build and Test
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build
        run: |
          xcodebuild clean build -project FireDispatchStatusApp.xcodeproj -scheme FireDispatchStatusApp -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro" CODE_SIGNING_REQUIRED=NO
